# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# flutter_application_path = '/Users/pankehong/Desktop/Flutter/flutter_ios/my_flutter'
# load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'PanSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # 集成Flutter项目
  # install_all_flutter_pods(flutter_application_path)

  # Pods for PanSwift
  pod 'PMetal', :path => '..'
  
  # post_install do |installer|
    # flutter_post_install(installer) if defined?(flutter_post_install)
  # end
  
end
